/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Currency = IDL.Record({
  'currencyCode' : IDL.Text,
  'amount' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const BrandInfo = IDL.Record({
  'craftsmanship' : IDL.Text,
  'mission' : IDL.Text,
  'values' : IDL.Text,
  'story' : IDL.Text,
  'heritage' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'featured' : IDL.Bool,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'updatedAt' : IDL.Int,
  'category' : IDL.Text,
  'colors' : IDL.Vec(IDL.Text),
  'price' : Currency,
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Currency,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getBrandInfo' : IDL.Func([], [BrandInfo], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateBrandInfo' : IDL.Func([BrandInfo], [], []),
  'uploadProductImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Currency = IDL.Record({
    'currencyCode' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const BrandInfo = IDL.Record({
    'craftsmanship' : IDL.Text,
    'mission' : IDL.Text,
    'values' : IDL.Text,
    'story' : IDL.Text,
    'heritage' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'featured' : IDL.Bool,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'updatedAt' : IDL.Int,
    'category' : IDL.Text,
    'colors' : IDL.Vec(IDL.Text),
    'price' : Currency,
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Currency,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getBrandInfo' : IDL.Func([], [BrandInfo], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateBrandInfo' : IDL.Func([BrandInfo], [], []),
    'uploadProductImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };