/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrandInfo {
  'craftsmanship' : string,
  'mission' : string,
  'values' : string,
  'story' : string,
  'heritage' : string,
}
export interface Category { 'name' : string, 'description' : string }
export interface Currency { 'currencyCode' : string, 'amount' : number }
export type ExternalBlob = Uint8Array;
export interface Product {
  'id' : bigint,
  'featured' : boolean,
  'inventory' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'sizes' : Array<string>,
  'updatedAt' : bigint,
  'category' : string,
  'colors' : Array<string>,
  'price' : Currency,
  'images' : Array<ExternalBlob>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCategory' : ActorMethod<[string, string], undefined>,
  'addProduct' : ActorMethod<
    [
      string,
      string,
      Currency,
      string,
      Array<ExternalBlob>,
      Array<string>,
      Array<string>,
      bigint,
      boolean,
    ],
    bigint
  >,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getBrandInfo' : ActorMethod<[], BrandInfo>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateBrandInfo' : ActorMethod<[BrandInfo], undefined>,
  'uploadProductImage' : ActorMethod<[bigint, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];